//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace QuantumAE.Validation.Resources;

using System.Globalization;
using System.Resources;

/// <summary>
/// hu: Erősen típusos erőforrás osztály lokalizált API válaszüzenetekhez.
/// <br />
/// en: A strongly-typed resource class for localized API response messages.
/// </summary>
public static class ApiResponseMessages
{
  private static ResourceManager? _resourceManager;

  /// <summary>
  /// hu: ResourceManager példány
  /// <br />
  /// en: ResourceManager instance
  /// </summary>
  public static ResourceManager ResourceManager
  {
    get
    {
      _resourceManager ??= new ResourceManager(
        "QuantumAE.Validation.Resources.ApiResponseMessages",
        typeof(ApiResponseMessages).Assembly);
      return _resourceManager;
    }
  }

  /// <summary>
  /// hu: Az aktuális kultúra a string kereséshez
  /// <br />
  /// en: Current culture for string lookup
  /// </summary>
  public static CultureInfo? Culture { get; set; }

  /// <summary>
  /// hu: The field '{0}' must be a string.
  /// </summary>
  public static string FieldMustBeString => ResourceManager.GetString("FieldMustBeString", Culture) ?? "The field '{0}' must be a string.";

  /// <summary>
  /// hu: Invalid VatCode '{0}'. Valid codes: {1}
  /// </summary>
  public static string Order_InvalidVatCode => ResourceManager.GetString("Order_InvalidVatCode", Culture) ?? "Invalid VatCode '{0}'. Valid codes: {1}";

  /// <summary>
  /// hu: Invalid Barcode '{0}'. Must be EAN-8 (8 digits) or EAN-13 (13 digits).
  /// </summary>
  public static string Order_InvalidBarcode => ResourceManager.GetString("Order_InvalidBarcode", Culture) ?? "Invalid Barcode '{0}'. Must be EAN-8 (8 digits) or EAN-13 (13 digits).";

  /// <summary>
  /// hu: Cannot mix old and new payment modes.
  /// </summary>
  public static string Order_PaymentModeMix => ResourceManager.GetString("Order_PaymentModeMix", Culture) ?? "Cannot mix old (Amount/Method) and new (Cash/Card/Szep/Afr) payment modes.";

  /// <summary>
  /// hu: Total paid ({0}) is less than order total ({1}).
  /// </summary>
  public static string Order_InsufficientPayment => ResourceManager.GetString("Order_InsufficientPayment", Culture) ?? "Total paid ({0}) is less than order total ({1}).";

  /// <summary>
  /// hu: VatStatus is required for invoices.
  /// </summary>
  public static string Order_VatStatusRequired => ResourceManager.GetString("Order_VatStatusRequired", Culture) ?? "VatStatus is required for invoices (DOMESTIC, OTHER, or PRIVATE_PERSON).";

  /// <summary>
  /// hu: Invalid VatStatus '{0}'. Valid values: {1}
  /// </summary>
  public static string Order_InvalidVatStatus => ResourceManager.GetString("Order_InvalidVatStatus", Culture) ?? "Invalid VatStatus '{0}'. Valid values: {1}";

  /// <summary>
  /// hu: TaxNumber is required when VatStatus is DOMESTIC.
  /// </summary>
  public static string Order_TaxNumberRequired => ResourceManager.GetString("Order_TaxNumberRequired", Culture) ?? "TaxNumber is required when VatStatus is DOMESTIC.";

  /// <summary>
  /// hu: CommunityVatNumber or ThirdStateTaxId is required when VatStatus is OTHER.
  /// </summary>
  public static string Order_CommunityOrThirdStateTaxIdRequired => ResourceManager.GetString("Order_CommunityOrThirdStateTaxIdRequired", Culture) ?? "CommunityVatNumber or ThirdStateTaxId is required when VatStatus is OTHER.";
}
