//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace QuantumAE.Validation.Resources;

using System.Globalization;
using System.Resources;

/// <summary>
/// hu: Erősen típusos erőforrás osztály lokalizált validációs üzenetekhez.
/// <br />
/// en: A strongly-typed resource class for localized validation messages.
/// </summary>
public static class ValidationMessages
{
  private static ResourceManager? _resourceManager;

  /// <summary>
  /// hu: ResourceManager példány
  /// <br />
  /// en: ResourceManager instance
  /// </summary>
  public static ResourceManager ResourceManager
  {
    get
    {
      _resourceManager ??= new ResourceManager(
        "QuantumAE.Validation.Resources.ValidationMessages",
        typeof(ValidationMessages).Assembly);
      return _resourceManager;
    }
  }

  /// <summary>
  /// hu: Az aktuális kultúra a string kereséshez
  /// <br />
  /// en: Current culture for string lookup
  /// </summary>
  public static CultureInfo? Culture { get; set; }

  /// <summary>
  /// hu: The field '{0}' is required.
  /// </summary>
  public static string Required => ResourceManager.GetString("Required", Culture) ?? "The field '{0}' is required.";

  /// <summary>
  /// hu: {0} is required.
  /// </summary>
  public static string Required_Simple => ResourceManager.GetString("Required_Simple", Culture) ?? "{0} is required.";

  /// <summary>
  /// hu: Either '{0}' or '{1}' must be provided.
  /// </summary>
  public static string RequiredIfEmpty => ResourceManager.GetString("RequiredIfEmpty", Culture) ?? "Either '{0}' or '{1}' must be provided.";

  /// <summary>
  /// hu: The field '{0}' must not be empty or whitespace.
  /// </summary>
  public static string NotEmptyString => ResourceManager.GetString("NotEmptyString", Culture) ?? "The field '{0}' must not be empty or whitespace.";

  /// <summary>
  /// hu: The field '{0}' must be positive.
  /// </summary>
  public static string PositiveDecimal => ResourceManager.GetString("PositiveDecimal", Culture) ?? "The field '{0}' must be positive.";

  /// <summary>
  /// hu: The field '{0}' must be zero or positive.
  /// </summary>
  public static string PositiveDecimal_AllowZero => ResourceManager.GetString("PositiveDecimal_AllowZero", Culture) ?? "The field '{0}' must be zero or positive.";

  /// <summary>
  /// hu: The field '{0}' must be a numeric type.
  /// </summary>
  public static string PositiveDecimal_NotNumeric => ResourceManager.GetString("PositiveDecimal_NotNumeric", Culture) ?? "The field '{0}' must be a numeric type.";

  /// <summary>
  /// hu: The field '{0}' must not exceed {1} characters.
  /// </summary>
  public static string StringLength_Max => ResourceManager.GetString("StringLength_Max", Culture) ?? "The field '{0}' must not exceed {1} characters.";

  /// <summary>
  /// hu: The field '{0}' must be between {1} and {2} characters.
  /// </summary>
  public static string StringLength_Range => ResourceManager.GetString("StringLength_Range", Culture) ?? "The field '{0}' must be between {1} and {2} characters.";

  /// <summary>
  /// hu: The field '{0}' must be between {1} and {2}.
  /// </summary>
  public static string Range => ResourceManager.GetString("Range", Culture) ?? "The field '{0}' must be between {1} and {2}.";

  /// <summary>
  /// hu: The field '{0}' must be at least {1}.
  /// </summary>
  public static string Min => ResourceManager.GetString("Min", Culture) ?? "The field '{0}' must be at least {1}.";

  /// <summary>
  /// hu: The field '{0}' must be greater than {1}.
  /// </summary>
  public static string Min_Exclusive => ResourceManager.GetString("Min_Exclusive", Culture) ?? "The field '{0}' must be greater than {1}.";

  /// <summary>
  /// hu: The field '{0}' must be at most {1}.
  /// </summary>
  public static string Max => ResourceManager.GetString("Max", Culture) ?? "The field '{0}' must be at most {1}.";

  /// <summary>
  /// hu: The field '{0}' must be less than {1}.
  /// </summary>
  public static string Max_Exclusive => ResourceManager.GetString("Max_Exclusive", Culture) ?? "The field '{0}' must be less than {1}.";

  /// <summary>
  /// hu: RequestId is required.
  /// </summary>
  public static string Order_RequestIdRequired => ResourceManager.GetString("Order_RequestIdRequired", Culture) ?? "RequestId is required.";

  /// <summary>
  /// hu: OrderId is required.
  /// </summary>
  public static string Order_OrderIdRequired => ResourceManager.GetString("Order_OrderIdRequired", Culture) ?? "OrderId is required.";

  /// <summary>
  /// hu: Item is required.
  /// </summary>
  public static string Order_ItemRequired => ResourceManager.GetString("Order_ItemRequired", Culture) ?? "Item is required.";

  /// <summary>
  /// hu: Customer is required for invoice.
  /// </summary>
  public static string Order_CustomerRequired => ResourceManager.GetString("Order_CustomerRequired", Culture) ?? "Customer is required for invoice.";

  /// <summary>
  /// hu: ReturnInfo is required for return document.
  /// </summary>
  public static string Order_ReturnInfoRequired => ResourceManager.GetString("Order_ReturnInfoRequired", Culture) ?? "ReturnInfo is required for return document.";

  /// <summary>
  /// hu: StornoInfo is required for storno document.
  /// </summary>
  public static string Order_StornoInfoRequired => ResourceManager.GetString("Order_StornoInfoRequired", Culture) ?? "StornoInfo is required for storno document.";

  /// <summary>
  /// hu: FuelCardClose is required for fuel card document.
  /// </summary>
  public static string Order_FuelCardCloseRequired => ResourceManager.GetString("Order_FuelCardCloseRequired", Culture) ?? "FuelCardClose is required for fuel card document.";

  /// <summary>
  /// hu: Either Name or Barcode must be provided.
  /// </summary>
  public static string Order_NameOrBarcodeRequired => ResourceManager.GetString("Order_NameOrBarcodeRequired", Culture) ?? "Either Name or Barcode must be provided.";
}
